#!/bin/bash

npx google-closure-compiler \
--language_in ECMASCRIPT5_STRICT \
--language_out ECMASCRIPT5_STRICT \
--warning_level DEFAULT \
--compilation_level WHITESPACE_ONLY \
--isolation_mode IIFE \
--js "./../../lib/rune.js" \
--js "./../../src/scope/Manifest.js" \
--js "./../../src/data/resource/Requests.js" \
--js "./../../src/entity/hud/CountDown.js" \
--js "./../../src/entity/effect/Particle.js" \
--js "./../../src/entity/hud/HighscoreList.js" \
--js "./../../src/entity/hud/Pointer.js" \
--js "./../../src/scene/gameover/NewHighscore.js" \
--js "./../../src/scene/gameover/GameOver.js" \
--js "./../../src/entity/hud/LiveScore.js" \
--js "./../../src/entity/hud/BonusContainer.js" \
--js "./../../src/entity/player/Bullet.js" \
--js "./../../src/entity/player/Gun.js" \
--js "./../../src/entity/enemy/Enemy.js" \
--js "./../../src/entity/enemy/Enemies.js" \
--js "./../../src/entity/player/Player.js" \
--js "./../../src/map/Map.js" \
--js "./../../src/scene/game/Game.js" \
--js "./../../src/scene/joinGame/JoinGame.js" \
--js "./../../src/scene/credits/Credits.js" \
--js "./../../src/scene/howtoPlay/HowtoPlay.js" \
--js "./../../src/scene/highscores/Highscores.js" \
--js "./../../src/scene/menu/Menu.js" \
--js "./../../src/system/Main.js" \
--js "./../../src/scope/Alias.js" \
--js_output_file "./../../dist/ArcticMadness.js";